# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Doodles
email: melanie@imfeld.info
description: > # this means to ignore newlines until "baseurl:"
  A blog for small projects
baseurl: "" # the subpath of your site, e.g. /blog
url: https://melanieimfeld.github.io
twitter_username: jekyllrb
github_username:  jekyll
facebook:
 app_id: 1234
 publisher: 1234
 admins: 1234
 logo: https://github.com/melanieimfeld/melanieimfeld.github.io/blob/master/assets/favicon_large-1.png # URL to a site-wide logo (e.g., /assets/your-company-logo.png)

social:
  name: #Ben Balter
  links:
    https://melanie.imfeld.info
    #- https://www.facebook.com/ben.balter
    #- https://www.linkedin.com/in/BenBalter
    #- https://plus.google.com/+BenBalter
    #- https://github.com/benbalter
    #- https://keybase.io/benbalter

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234

# Google services
google_analytics: UA—108361669-1
    
# Build settings
markdown: kramdown
theme: 
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji 

  
#jekyll-mentions:
#  base_url: https://twitter.com

tag_page_layout: tags
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

ignored_tags: [blog]

tag_page_data:
  sitemap: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
